import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

csvFrame = pd.read_csv('Technology in Life Survey.csv')
grade = input('What grade level do you want? (fre,sop,jun,sen,adu) ').lower()

if grade == 'fre':
    gradeWord = 'freshman'
    gradeFrame = csvFrame[csvFrame['What grade are you in?'].str.contains(gradeWord, case=False)]
    
    #extracts all the values from the formatted csv file to be used for the AI model
    true = gradeFrame['Did you ever get hacked?'].apply(
        lambda x: 1 if 'Yes' in str(x) else 0
        ).values
    
    reuse = gradeFrame["Do you reuse passwords for multiple accounts? "].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    shortPassword = gradeFrame["If you reuse the same password, Is your password short/easy or long/complex?"].apply(
        lambda x: 1 if "Short" in str(x) else 0
    ).values

    leaked = gradeFrame["Has your password ever gotten leaked in a data leak? Example below.\n"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    autoGenerated = gradeFrame["Have you ever used an automatically generated/recommended password?"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values


elif grade == 'sop':
    gradeWord = 'soph'
    gradeFrame = csvFrame[csvFrame['What grade are you in?'].str.contains(gradeWord, case=False)]
    
    #extracts all the values from the formatted csv file to be used for the AI model
    true = gradeFrame['Did you ever get hacked?'].apply(
        lambda x: 1 if 'Yes' in str(x) else 0
        ).values
    
    reuse = gradeFrame["Do you reuse passwords for multiple accounts? "].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    shortPassword = gradeFrame["If you reuse the same password, Is your password short/easy or long/complex?"].apply(
        lambda x: 1 if "Short" in str(x) else 0
    ).values

    leaked = gradeFrame["Has your password ever gotten leaked in a data leak? Example below.\n"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    autoGenerated = gradeFrame["Have you ever used an automatically generated/recommended password?"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values


elif grade == 'jun':
    gradeWord = 'junior'
    gradeFrame = csvFrame[csvFrame['What grade are you in?'].str.contains(gradeWord, case=False)]
    
    #extracts all the values from the formatted csv file to be used for the AI model
    true = gradeFrame['Did you ever get hacked?'].apply(
        lambda x: 1 if 'Yes' in str(x) else 0
        ).values
    
    reuse = gradeFrame["Do you reuse passwords for multiple accounts? "].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    shortPassword = gradeFrame["If you reuse the same password, Is your password short/easy or long/complex?"].apply(
        lambda x: 1 if "Short" in str(x) else 0
    ).values

    leaked = gradeFrame["Has your password ever gotten leaked in a data leak? Example below.\n"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    autoGenerated = gradeFrame["Have you ever used an automatically generated/recommended password?"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

elif grade == 'sen':
    gradeWord = 'senior'
    gradeFrame = csvFrame[csvFrame['What grade are you in?'].str.contains(gradeWord, case=False)]
    
    #extracts all the values from the formatted csv file to be used for the AI model
    true = gradeFrame['Did you ever get hacked?'].apply(
        lambda x: 1 if 'Yes' in str(x) else 0
        ).values
    
    reuse = gradeFrame["Do you reuse passwords for multiple accounts? "].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    shortPassword = gradeFrame["If you reuse the same password, Is your password short/easy or long/complex?"].apply(
        lambda x: 1 if "Short" in str(x) else 0
    ).values

    leaked = gradeFrame["Has your password ever gotten leaked in a data leak? Example below.\n"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    autoGenerated = gradeFrame["Have you ever used an automatically generated/recommended password?"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values


elif grade == 'adu':
    gradeWord = 'adult'
    gradeFrame = csvFrame[csvFrame['What grade are you in?'].str.contains(gradeWord, case=False)]
    
    #extracts all the values from the formatted csv file to be used for the AI model
    true = gradeFrame['Did you ever get hacked?'].apply(
        lambda x: 1 if 'Yes' in str(x) else 0
        ).values
    
    reuse = gradeFrame["Do you reuse passwords for multiple accounts? "].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    shortPassword = gradeFrame["If you reuse the same password, Is your password short/easy or long/complex?"].apply(
        lambda x: 1 if "Short" in str(x) else 0
    ).values

    leaked = gradeFrame["Has your password ever gotten leaked in a data leak? Example below.\n"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values

    autoGenerated = gradeFrame["Have you ever used an automatically generated/recommended password?"].apply(
        lambda x: 1 if "Yes" in str(x) else 0
    ).values


'''
print(pd.crosstab(true, reuse))
print(pd.crosstab(true, shortPassword))
print(pd.crosstab(true, leaked))
print(pd.crosstab(true, autoGenerated))


print(pd.crosstab([shortPassword, reuse], true))
'''

#does not include short password since the influence is miniscule (0.005)


if grade == 'sop':
    scores = (
        0.2 * reuse -
        0.08 * leaked -
        #subtracts auto generated passwords due to them making it more safe for the user to not get hacked
        0.05 * autoGenerated +
        0.05 * shortPassword
    )
    scores += 0.09*(leaked*reuse)
elif grade == 'jun':
    scores = (
        -0.12*reuse-
        0.08*leaked-
        0.05*autoGenerated-
        0.08*shortPassword
    )
    scores += 0.09*(leaked*reuse)
else:
    scores = (
        0.2 * reuse +
        0.55 * leaked -
        #subtracts auto generated passwords due to them making it more safe for the user to not get hacked
        0.26 * autoGenerated +
        0.05 * shortPassword
    )
    scores += 0.2*(leaked*reuse)
scores += 0.03*(shortPassword*leaked)
scores += 0.1 * ((leaked+reuse+shortPassword) > 2).astype(int)
#makes sure no scores are negative (someone who is 0001 would have been a negative risk which isn't possible)
scores = np.clip(scores, 0, 1)
thresholds = np.linspace(0, 1, 100)

#gets the lists of true positive rate and false positive rate
tprList = []
fprList = []

#checks how the model behaves in every scenario from having everyone hacked (0 threshold), to having almost no one hacked (1 threshold)
for threshold in thresholds:
    
    #predict that the user is hacked (1) if score is above or equal to the threshold, else it is 0 for not being hacked
    predictions = (scores >= threshold).astype(int)
    
    #number of false/true positives/negatives
    tp = np.sum((predictions == 1) & (true == 1))
    fp = np.sum((predictions == 1) & (true == 0))
    tn = np.sum((predictions == 0) & (true == 0))
    fn = np.sum((predictions == 0) & (true == 1))
    
    #calculates the individual true positive rate and false positive rate for the specific threshold
    tpr = tp/(tp+fn) if (tp+fn) > 0 else 0
    fpr = fp/(fp+tn) if (fp+tn) > 0 else 0
    
    tprList.append(tpr)
    fprList.append(fpr)

#calculates the area under the curve (the real ROC AUC)
auc = 0
for i in range(1, len(fprList)):
    width = fprList[i] - fprList[i-1]
    height = (tprList[i] + tprList[i-1])/2
    auc += width*height

print(f'ROC AUC: {round(abs(auc), 3)}')

plt.plot(fprList, tprList)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()


#whitespace
